"""Renamed column in User model

Revision ID: 06262e2f42e9
Revises: 73ce9f4ac080
Create Date: 2024-06-28 10:40:39.014523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06262e2f42e9'
down_revision = '73ce9f4ac080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=70), nullable=True))
        batch_op.drop_index('uq_user_login')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.drop_column('login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_index('uq_user_login', ['login'], unique=True)
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
