"""Initial migration.

Revision ID: 1aed80fce78d
Revises: 
Create Date: 2024-06-26 09:52:45.723922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aed80fce78d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postcodes'))
    )
    op.create_table('suburbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('NEW_SOUTH_WALES', 'VICTORIA', 'QUEENSLAND', 'SOUTH_AUSTRALIA', 'WESTERN_AUSTRALIA', 'TASMANIA', 'NORTHERN_TERRITORY', 'AUSTRALIAN_CAPITAL_TERRITORY', name='state'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suburbs'))
    )
    op.create_table('postcode_suburb',
    sa.Column('postcode_id', sa.Integer(), nullable=True),
    sa.Column('suburb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postcode_id'], ['postcodes.id'], name=op.f('fk_postcode_suburb_postcode_id_postcodes')),
    sa.ForeignKeyConstraint(['suburb_id'], ['suburbs.id'], name=op.f('fk_postcode_suburb_suburb_id_suburbs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcode_suburb')
    op.drop_table('suburbs')
    op.drop_table('postcodes')
    # ### end Alembic commands ###
