"""second migrate

Revision ID: 3daaae6931fb
Revises: 77861eb263a9
Create Date: 2024-07-11 12:14:11.716216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3daaae6931fb'
down_revision = '77861eb263a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_reporting', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('state',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('avg_price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_reporting', schema=None) as batch_op:
        batch_op.alter_column('avg_price',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=10),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
