"""first migration

Revision ID: 77861eb263a9
Revises: 
Create Date: 2024-07-11 11:40:46.514373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77861eb263a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcode_suburb',
    sa.Column('postcode_id', sa.Integer(), nullable=False),
    sa.Column('suburb_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postcode_id'], ['postcodes.id'], name=op.f('fk_postcode_suburb_postcode_id_postcodes')),
    sa.ForeignKeyConstraint(['suburb_id'], ['suburbs.id'], name=op.f('fk_postcode_suburb_suburb_id_suburbs')),
    sa.PrimaryKeyConstraint('postcode_id', 'suburb_id', name=op.f('pk_postcode_suburb'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcode_suburb')
    # ### end Alembic commands ###
