"""fresh start

Revision ID: 8a37640a0fbe
Revises: 
Create Date: 2024-06-28 14:59:03.870223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a37640a0fbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postcodes')),
    sa.UniqueConstraint('postcode', name=op.f('uq_postcodes_postcode'))
    )
    op.create_table('suburbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('NEW_SOUTH_WALES', 'VICTORIA', 'QUEENSLAND', 'SOUTH_AUSTRALIA', 'WESTERN_AUSTRALIA', 'TASMANIA', 'NORTHERN_TERRITORY', 'AUSTRALIAN_CAPITAL_TERRITORY', name='state'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suburbs')),
    sa.UniqueConstraint('name', name=op.f('uq_suburbs_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('public_id', name=op.f('uq_user_public_id')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('postcode_suburb',
    sa.Column('postcode_id', sa.Integer(), nullable=True),
    sa.Column('suburb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postcode_id'], ['postcodes.id'], name=op.f('fk_postcode_suburb_postcode_id_postcodes')),
    sa.ForeignKeyConstraint(['suburb_id'], ['suburbs.id'], name=op.f('fk_postcode_suburb_suburb_id_suburbs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcode_suburb')
    op.drop_table('user')
    op.drop_table('suburbs')
    op.drop_table('postcodes')
    # ### end Alembic commands ###
