"""Initial migration.

Revision ID: e8c1c471addd
Revises: 
Create Date: 2024-06-24 23:04:21.147106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c1c471addd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('hexCode', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colour')),
    sa.UniqueConstraint('hexCode', name=op.f('uq_colour_hexCode')),
    sa.UniqueConstraint('name', name=op.f('uq_colour_name'))
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.Column('dueDate', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('task', sa.String(length=500), nullable=False),
    sa.Column('isComplete', sa.Boolean(), nullable=True),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], name=op.f('fk_todo_colour_id_colour')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('colour')
    # ### end Alembic commands ###
